name: Format

on:
  push:
    branches:
      - main

jobs:
  format:
    name: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Lint code with Ruff
        run: uv run ruff check --output-format=github

      - name: Check code formatting with Ruff
        run: uv run ruff format --diff
